#!/bin/ksh

## this version takes a file name parameter WITHOUT extension
## and produces the asm code output file

good="true" ;

if [[ -f $1.cpp ]] then
  suff=cpp
  exe=g++ ;
  
  elif [[ -f $1.cc ]] then
      suff=cc
      exe=g++ ;

  elif [[ -f $1.c ]] then
      suff=c
      exe=gcc ;

  elif [[ -f $1.nc ]] then
      suff=nc
      exe=gcc ;

  else
      good="false"
      echo "No valid file with name '$1' " ;

fi       

if [[ ${good} = "true" ]] then
  /opt/solaris7/bin/${exe} -S -fverbose-asm $1.${suff}
fi
