#!/bin/ksh

## this version takes a file name parameter and does
## a C or C++ compile, depending on the filename extension
## -o sets name for output file

param=$1
if [[ ${#param} == 0 ]] then
  echo "Usage: gcr 'file_to_compile' "
  exit ;
fi

## take off the filename extension if present
name=${param%%.*} ;

if [[ -f ${name}.cpp ]] then
  suff=cpp
  exe=g++ ;
  
  elif [[ -f ${name}.cc ]] then
      suff=cc
      exe=g++ ;

  elif [[ -f ${name}.C ]] then
      suff=C
      exe=g++ ;

  elif [[ -f ${name}.c ]] then
      suff=c
      exe=gcc ;

  elif [[ -f ${name}.nc ]] then
      suff=nc
      exe=gcc ;

  else
      good="false"
      echo "No valid file with name '$1' " 
      exit ;
fi       

/opt/solaris7/bin/${exe} -o ${name} ${name}.${suff}
