#!/bin/ksh

## this version takes a file name parameter WITHOUT suffix
## and does a C compile
## -o sets name for output file


good="true" ;

if [[ -f $1.c ]] then
      suff=c

  elif [[ -f $1.nc ]] then
      suff=nc

  else
      good="false"
      echo "No valid file with name '$1' " ;

fi       

if [[ ${good} = "true" ]] then
  /opt/solaris7/bin/gcc -o $1.x $1.${suff}
fi
