#!/bin/ksh

## this version takes a file name parameter WITHOUT suffix
## and does a C++ compile
## -o sets name for output file
## -g creates debug info


good="true" ;

if [[ -f $1.cpp ]] then
      suff=cpp

  elif [[ -f $1.cc ]] then
      suff=cc

  elif [[ -f $1.C ]] then
      suff=C

  else
      good="false"
      echo "No valid file with name '$1' " ;
fi       


if [[ ${good} = "true" ]] then
  /opt/solaris7/bin/g++ -g -o $1.x $1.${suff}
fi
