#!/bin/sh
#
#  Script:		start_netscape
#  Instance:		1
#  %version:		2 %
#  Description:		launch Netscape
#
#  %created_by:		pgjeann %
#  %date_created:	Wed Jan 10 16:17:28 EDT 2001 %
######################################################################

echo >> $HOME/DT.log
echo $0 $* >> $HOME/DT.log
XVIEW_DIR=/opt/CSEscape4.75

LD_LIBRARY_PATH=${XVIEW_DIR}
export LD_LIBRARY_PATH

MOZILLA_HOME=/opt/netscape
export MOZILLA_HOME

exec ${XVIEW_DIR}/netscape $2
