#!/bin/bash
################################################################################
#
# mhsatto@cse-cst.gc.ca
# $Id: bashrc,v 1.21 2010/09/20 13:56:57 mhsatto Exp $
#
################################################################################

# set prompt
if [ ! $HAVENEWPROMPT ]
then
    RED="\[\e[31;1m\]"
    GREEN="\[\e[32;1m\]"
    YELLOW="\[\e[33;1m\]"
    BLUE="\[\e[34;1m\]"
    MAGENTA="\[\e[35;1m\]"
    CYAN="\[\e[36;2m\]"
    COLOR_RESET="\[\e[30;0m\]"
    TXTFRAME=$RED
    HILITE=$YELLOW
    export PS1="${HILITE}\u@\h${TXTFRAME} | ${HILITE}\t${TXTFRAME} | ${HILITE}\w${TXTFRAME}\r\n${HILITE}\!${TXTFRAME} >$COLOR_RESET "
    HAVENEWPROMPT='TRUE'
fi

# set manpath
if [ ! $HAVEORIGMANPATH ]
then
	ORIGMANPATH=$MANPATH
    HAVEORIGMANPATH='TRUE'
fi
export MANPATH=~/dev/man:~/gnu/man:$ORIGMANPATH

# set infopath
if [ ! $HAVEORIGINFOPATH ]
then
	ORIGINFOPATH=$INFOPATH
    HAVEORIGINFOPATH='TRUE'
fi
export INFOPATH=~/dev/info:~/gnu/info:$ORIGINFOPATH

# reset libpath
if [ $HAVEORIGLIBPATH ]
then
    export LD_LIBRARY_PATH=$ORIGLIBPATH
fi
ADDLIBPATH=~/dev/lib:~/gnu/lib:~/dev/lib64:~/gnu/lib64
export LD_LIBRARY_PATH=$ADDLIBPATH:$LD_LIBRARY_PATH

# reset path and load Open Projects
cleanopen
if [ $HAVEORIGPATH ]
then
    export PATH=$ORIGPATH
fi
source /project/open/open_env.sh
unset LDFLAGS

# Netezza setup
source ~/dev/scripts/nz.sh

# MEGRAPHS/MTGL setup
source ~/dev/scripts/megraphs.sh

# omniORB setup
#source ~/dev/scripts/omni.sh

# make sure my path folders are first
EXTENDEDPATH=$PATH
MYPATH=~/bin:~/dev/bin:~/gnu/bin:~/dev/perl:~/dev/sbin:~/gnu/sbin:/sbin
export PATH=$MYPATH:$EXTENDEDPATH

# functions
source ~/bin/src/bash.fxn
alias sobf='source ~/bin/src/bash.fxn'

# aliases
source ~/bin/src/bash.als
alias soba='source ~/bin/src/bash.als'

########################################
# END OF SCRIPT
BASHRC_LOADED='TRUE'
echo "LOADED ~/.bashext"
# END OF SCRIPT
########################################
