#!/bin/csh

if ( $?HOST    == 0 ) setenv HOST `uname -n`
if ( $?MANPATH == 0 ) setenv MANPATH /usr/dt/man:/usr/man:/usr/openwin/share/man:/opt/solaris7/man

set path = (/usr/bin /usr/dt/bin /opt/solaris7/bin /usr/ccs/bin /bin /usr/xpg4/bin)
set path = ($path /usr/sbin /usr/openwin/bin /usr/ucb ~mhsatto/bin ~mhsatto/refer/perl)
set noclobber
set filec
set savehist=300
set history=500

setenv	MANPATH	${MANPATH}:/opt/solaris7/GNU/gcc-2.95.2/man:/opt/solaris7/GNU/gzip-1.2.4a/man
setenv	EDITOR	/usr/local/bin/nedit

# FMHOME line added by the FrameMaker user's setup program
setenv FMHOME /opt/frame-5.5.6
set path = ($path $FMHOME/bin)

alias	ls	'ls -F'
alias	c	clear
alias	m	more
alias	path	"echo $PATH | tr ':' '\n' "
alias	manpath	"echo $MANPATH | tr ':' '\n' "
alias	display	'echo $DISPLAY'
alias	so	'source'
alias	show	'pwd; ls -lt |more '
alias	setbox	'echo -n "]0; \!* " '
alias	h	'history 17'
alias	p	'set prompt = "[1;35;49m[${USER}@${HOST}] `pwd` ! > [0m" '
alias	cd	'cd \!*; p'
alias	push	'pushd \!*; p'
alias	pop	'popd \!*; p'

if ( -f ~mhsatto/bin/cals ) source ~mhsatto/bin/cals

stty erase ^H werase ^W rprnt ^R flush ^Y

p

echo "[${HOST}].cshrem has been read."
